[package]
name = "faster-rs"
version = "0.1.0"
authors = ["Max Meldrum <mmeldrum@kth.se>"]
edition = "2018"

[dependencies]
libc = "0.2"
libfaster-sys = { path = "libfaster-sys", version = "0.1.0" }

