[package]
name = "libfaster-sys"
version = "0.1.0"
authors = ["Max Meldrum <mmeldrum@kth.se>"]
edition = "2018"

build = "build.rs"
links = "faster"

[dependencies]
libc = "0.2"

[build-dependencies]
bindgen = "0.43.1"
cmake = "0.1"


