[package]
name = "libfaster-sys"
version = "0.1.0"
authors = ["Max Meldrum <mmeldrum@kth.se>"]
edition = "2018"

build = "build.rs"
links = "fasterc"

[dependencies]
libc = "0.2"


[build-dependencies]
cc = { version = "^1.0", features = ["parallel"] }
bindgen = "0.43.1"

